jobs:
  - script: >
      pipelineJob('UploadPolicies') {
          definition {
              cpsScm {
                  scriptPath 'jenkins/upload-policyies.groovy'
                  scm {
                    git {
                        remote { url 'https://github.com/mbaitelman/chef-policy-cookbook.git' }
                        branch 'master'
                    }
                  }
              }
          }
      }