jobs:
  - script: >
      pipelineJob('UploadPolicies') {
          definition {
              cpsScm {
                  scriptPath 'jenkins/upload-policyies.groovy'
                  scm {
                    git {
                        remote { url 'https://github.com/mbaitelman/chef-policy-cookbook.git' }
                        branch 'master'
                    }
                  }
              }
          }
      }
  - script: >
      pipelineJob('PushPolicies') {
          definition {
              cpsScm {
                  scriptPath 'jenkins/push-policyies.groovy'
                  scm {
                    git {
                        remote { url 'https://github.com/mbaitelman/chef-policy-cookbook.git' }
                        branch 'master'
                    }
                  }
              }
          }
      }      
  - script: >
      pipelineJob('TestKitchen') {
          definition {
              cpsScm {
                  scriptPath 'jenkins/test-kitchen.groovy'
                  scm {
                    git {
                        remote { url 'https://github.com/mbaitelman/chef-policy-cookbook.git' }
                        branch 'master'
                    }
                  }
              }
          }
      }
  - script: >
      pipelineJob('Chef-CICF') {
          definition {
              cpsScm {
                  scriptPath 'jenkins/chef-cicd.groovy'
                  scm {
                    git {
                        remote { url 'https://github.com/mbaitelman/chef-policy-cookbook.git' }
                        branch 'master'
                    }
                  }
              }
          }
      }